In [42]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [6]:
iris=datasets.load_iris()

In [7]:
X=iris.data
Y=iris.target

In [8]:
X.shape

(150, 4)

In [9]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 10)


In [13]:
X_train.shape

(105, 4)

In [14]:
X_test.shape

(45, 4)

In [15]:
Y_test

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [16]:
model=LogisticRegression()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [18]:
metrics.accuracy_score(Y_test,Y_pred)

0.8888888888888888

In [19]:
metrics.confusion_matrix(Y_test,Y_pred)

array([[14,  0,  0],
       [ 0, 12,  5],
       [ 0,  0, 14]])

In [20]:
CR=metrics.classification_report(Y_test,Y_pred)
print(CR)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.71      0.83        17
          2       0.74      1.00      0.85        14

avg / total       0.92      0.89      0.89        45



# Kfold Cross Validation

In [56]:
kf=KFold(n_splits=5,shuffle=True,random_state=2)
acc=[]
for train,test in kf.split(X,Y):
    M=LogisticRegression()
    Xtrain,Xtest=X[train,:],X[test,:]
    Ytrain,Ytest=Y[train],Y[test]
    M.fit(Xtrain,Ytrain)
    Y_predict=M.predict(Xtest)
    acc.append(metrics.accuracy_score(Ytest,Y_predict))
print("Cross-validated Score:%.2f%% " % np.mean(acc))    

Cross-validated Score:0.95% 


In [57]:
acc

[0.9333333333333333,
 0.9666666666666667,
 0.9333333333333333,
 0.9333333333333333,
 0.9666666666666667]